<?xml version="1.0" encoding="UTF-8"?>
<!--

    <pre>
    The owner of the original code is Ciena Corporation.

    Portions created by the original owner are Copyright (C) 2004-2010
    the original owner. All Rights Reserved.

    Portions created by other contributors are Copyright (C) the contributor.
    All Rights Reserved.

    Contributor(s):
      (Contributors insert name & email here)

    This file is part of DRAC (Dynamic Resource Allocation Controller).

    DRAC is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    DRAC is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
    Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program.  If not, see <http://www.gnu.org/licenses/>.
    </pre>

-->

<definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
    xmlns:tns="http://www.opendrac.org/ws/NetworkMonitoringService_v3.0" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:wsaddr="http://www.w3.org/2006/05/addressing/wsdl" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    targetNamespace="http://www.opendrac.org/ws/NetworkMonitoringService_v3.0">
   <import namespace="http://www.opendrac.org/ws/NetworkMonitoringService_v3.0" location="./NetworkMonitoringServiceMessages_v3.0.wsdl"/>
   <binding name="NetworkMonitoringServiceSOAPBinding" type="tns:NetworkMonitoringServicePortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="queryEndpoints">
         <soap:operation soapAction="http://www.opendrac.org/ws/NetworkMonitoringService_v3.0/queryEndpoints" style="document"/>
         <input>
            <soap:header message="tns:Security" part="header" use="literal"/>
            <soap:body parts="payload" use="literal"/>
         </input>
         <output>
            <soap:body parts="payload" use="literal"/>
         </output>
         <fault name="fault">
            <soap:fault name="fault" use="literal"/>
         </fault>
      </operation>
      <operation name="queryEndpoint">
         <soap:operation soapAction="http://www.opendrac.org/ws/NetworkMonitoringService_v3.0/queryEndpoint" style="document"/>
         <input>
            <soap:header message="tns:Security" part="header" use="literal"/>
            <soap:body parts="payload" use="literal"/>
         </input>
         <output>
            <soap:body parts="payload" use="literal"/>
         </output>
         <fault name="fault">
            <soap:fault name="fault" use="literal"/>
         </fault>
      </operation>
   </binding>
   <service name="NetworkMonitoringService_v3.0">
      <documentation>
      NetworkMonitoringService allows clients to query information about the DRAC managed endpoints.
   </documentation>
      <port name="NetworkMonitoringServiceSOAPport" binding="tns:NetworkMonitoringServiceSOAPBinding">
         <soap:address location="https://localhost:8443/axis2/services/NetworkMonitoringService_v3.0"/>
      </port>
   </service>
</definitions>
