// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.surfnet.bod.physicalresourcegroup;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import org.surfnet.bod.physicalresourcegroup.PhysicalResourceGroup;

privileged aspect PhysicalResourceGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PhysicalResourceGroupDataOnDemand: @Component;
    
    private Random PhysicalResourceGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<PhysicalResourceGroup> PhysicalResourceGroupDataOnDemand.data;
    
    public PhysicalResourceGroup PhysicalResourceGroupDataOnDemand.getNewTransientPhysicalResourceGroup(int index) {
        PhysicalResourceGroup obj = new PhysicalResourceGroup();
        setInstitutionName(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void PhysicalResourceGroupDataOnDemand.setInstitutionName(PhysicalResourceGroup obj, int index) {
        String institutionName = "institutionName_" + index;
        obj.setInstitutionName(institutionName);
    }
    
    public void PhysicalResourceGroupDataOnDemand.setName(PhysicalResourceGroup obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public PhysicalResourceGroup PhysicalResourceGroupDataOnDemand.getSpecificPhysicalResourceGroup(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PhysicalResourceGroup obj = data.get(index);
        java.lang.Long id = obj.getId();
        return PhysicalResourceGroup.findPhysicalResourceGroup(id);
    }
    
    public PhysicalResourceGroup PhysicalResourceGroupDataOnDemand.getRandomPhysicalResourceGroup() {
        init();
        PhysicalResourceGroup obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return PhysicalResourceGroup.findPhysicalResourceGroup(id);
    }
    
    public boolean PhysicalResourceGroupDataOnDemand.modifyPhysicalResourceGroup(PhysicalResourceGroup obj) {
        return false;
    }
    
    public void PhysicalResourceGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PhysicalResourceGroup.findPhysicalResourceGroupEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PhysicalResourceGroup' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.surfnet.bod.physicalresourcegroup.PhysicalResourceGroup>();
        for (int i = 0; i < 10; i++) {
            PhysicalResourceGroup obj = getNewTransientPhysicalResourceGroup(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
