// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.surfnet.bod.domain;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import org.surfnet.bod.domain.PhysicalPortDataOnDemand;
import org.surfnet.bod.service.PhysicalPortService;

privileged aspect PhysicalPortIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhysicalPortIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhysicalPortIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhysicalPortIntegrationTest: @Transactional;
    
    @Autowired
    private PhysicalPortDataOnDemand PhysicalPortIntegrationTest.dod;
    
    @Autowired
    PhysicalPortService PhysicalPortIntegrationTest.physicalPortService;
    
    @Test
    public void PhysicalPortIntegrationTest.testCountAllPhysicalPorts() {
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", dod.getRandomPhysicalPort());
        long count = physicalPortService.countAllPhysicalPorts();
        Assert.assertTrue("Counter for 'PhysicalPort' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testFindPhysicalPort() {
        PhysicalPort obj = dod.getRandomPhysicalPort();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to provide an identifier", id);
        obj = physicalPortService.findPhysicalPort(id);
        Assert.assertNotNull("Find method for 'PhysicalPort' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PhysicalPort' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testFindAllPhysicalPorts() {
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", dod.getRandomPhysicalPort());
        long count = physicalPortService.countAllPhysicalPorts();
        Assert.assertTrue("Too expensive to perform a find all test for 'PhysicalPort', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PhysicalPort> result = physicalPortService.findAllPhysicalPorts();
        Assert.assertNotNull("Find all method for 'PhysicalPort' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PhysicalPort' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testFindPhysicalPortEntries() {
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", dod.getRandomPhysicalPort());
        long count = physicalPortService.countAllPhysicalPorts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PhysicalPort> result = physicalPortService.findPhysicalPortEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PhysicalPort' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PhysicalPort' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testFlush() {
        PhysicalPort obj = dod.getRandomPhysicalPort();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to provide an identifier", id);
        obj = physicalPortService.findPhysicalPort(id);
        Assert.assertNotNull("Find method for 'PhysicalPort' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhysicalPort(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PhysicalPort' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testUpdatePhysicalPortUpdate() {
        PhysicalPort obj = dod.getRandomPhysicalPort();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to provide an identifier", id);
        obj = physicalPortService.findPhysicalPort(id);
        boolean modified =  dod.modifyPhysicalPort(obj);
        Integer currentVersion = obj.getVersion();
        PhysicalPort merged = physicalPortService.updatePhysicalPort(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PhysicalPort' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testSavePhysicalPort() {
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", dod.getRandomPhysicalPort());
        PhysicalPort obj = dod.getNewTransientPhysicalPort(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PhysicalPort' identifier to be null", obj.getId());
        physicalPortService.savePhysicalPort(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'PhysicalPort' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhysicalPortIntegrationTest.testDeletePhysicalPort() {
        PhysicalPort obj = dod.getRandomPhysicalPort();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PhysicalPort' failed to provide an identifier", id);
        obj = physicalPortService.findPhysicalPort(id);
        physicalPortService.deletePhysicalPort(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'PhysicalPort' with identifier '" + id + "'", physicalPortService.findPhysicalPort(id));
    }
    
}
