// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.surfnet.bod.institution;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.surfnet.bod.institution.Institution;
import org.surfnet.bod.physicalresourcegroup.PhysicalResourceGroup;
import org.surfnet.bod.physicalresourcegroup.PhysicalResourceGroupDataOnDemand;

privileged aspect InstitutionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstitutionDataOnDemand: @Component;
    
    private Random InstitutionDataOnDemand.rnd = new SecureRandom();
    
    private List<Institution> InstitutionDataOnDemand.data;
    
    @Autowired
    private PhysicalResourceGroupDataOnDemand InstitutionDataOnDemand.physicalResourceGroupDataOnDemand;
    
    public Institution InstitutionDataOnDemand.getNewTransientInstitution(int index) {
        Institution obj = new Institution();
        setName(obj, index);
        setPhysicalResourceGroup(obj, index);
        return obj;
    }
    
    public void InstitutionDataOnDemand.setName(Institution obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void InstitutionDataOnDemand.setPhysicalResourceGroup(Institution obj, int index) {
        PhysicalResourceGroup physicalResourceGroup = physicalResourceGroupDataOnDemand.getRandomPhysicalResourceGroup();
        obj.setPhysicalResourceGroup(physicalResourceGroup);
    }
    
    public Institution InstitutionDataOnDemand.getSpecificInstitution(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Institution obj = data.get(index);
        java.lang.Long id = obj.getId();
        return Institution.findInstitution(id);
    }
    
    public Institution InstitutionDataOnDemand.getRandomInstitution() {
        init();
        Institution obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return Institution.findInstitution(id);
    }
    
    public boolean InstitutionDataOnDemand.modifyInstitution(Institution obj) {
        return false;
    }
    
    public void InstitutionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Institution.findInstitutionEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Institution' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.surfnet.bod.institution.Institution>();
        for (int i = 0; i < 10; i++) {
            Institution obj = getNewTransientInstitution(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
